### ISSUE TITLE
Commands are not tab-able in command blocks.

### ISSUE THREAD

**Issue by DrakDv** [TemplexMC/VanillaMode#2]
[VM-2] Tab-Commands: The _first_ part of each command, the command itself (not arguments), is not able to be tabbed in command blocks.

**Comment by addisoncrump** [comment]
This has to do with how I intercept tab for help injection. I can fix this with a cheaty workaround, though.

**Comment by addisoncrump** [comment]
This issue is existing in standard bukkit as well, and solving it for command blocks would create issues in chat.

**Comment by addisoncrump** [comment]
A workaround for this issue is to prepend command block commands with `/` and _then_ use tab.
